{% set min_rust = "rust >=1.60" %}
{% set version = "0.2.1" %}

package:
  name: reasonable
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/reasonable/reasonable-{{ version }}.tar.gz
  sha256: 3ee35e4a4d136ff386f04c3b980a3571da424fc264979f6767104fac2274eeaa

build:
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}                    # [unix]
    - {{ compiler('cxx') }}                  # [unix]
    - {{ compiler('m2w64_c') }}              # [win]
    - {{ compiler('m2w64_cxx') }}            # [win]
    - {{ min_rust }}
    - cargo-bundle-licenses
    - clangdev                               # [not osx]
    - llvmdev                                # [not osx]
    - maturin >=0.14.0,<0.15.0
    - m2w64-binutils                         # [win]
  host:
    - pip
    - python
  run:
    - python
  run_constrained:
    - rdflib >=6.1

test:
  imports:
    - reasonable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gtfierro/reasonable
  summary: An OWL 2 RL reasoner with reasonable performance
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
