{% set version = "0.1.61" %}

package:
  name: reasonable
  version: {{ version }}

source:
  url: https://github.com/gtfierro/reasonable/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b1591452d0fa5e46d08ba0af664e5c512ba362a03d14acff7680cd0de27f052a

build:
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}                    # [unix]
    - {{ compiler('cxx') }}                  # [unix]
    - {{ compiler('m2w64_c') }}              # [win]
    - {{ compiler('m2w64_cxx') }}            # [win]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - pip
    - maturin >=0.13,<0.14
    - python
  run:
    # as listed in pyproject.toml, but doesn't seem to fail `pip check` without
    # - cffi >=1.15.1,<1.16
    - python
  run_constrained:
    - rdflib >=6.1

test:
  imports:
    - reasonable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gtfierro/reasonable
  summary: An OWL 2 RL reasoner with reasonable performance
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
