# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.4.4"
  cargo_wrapper: cargo-auditable-wrapper${{ ".sh" if unix else ".bat" }}
  python_check_max: "3.14"

package:
  name: reasonable
  version: ${{ version }}

source:
  - target_directory: dist
    url: https://files.pythonhosted.org/packages/source/r/reasonable/reasonable-${{ version }}.tar.gz
    sha256: dac7b568b5e5237ec03250dc35b786a60c32d844a94d691c3bff0b0d86f40fd5
  - target_directory: src
    url: https://github.com/gtfierro/reasonable/releases/download/v${{ version }}/reasonable_v${{ version }}.tar.gz
    sha256: 7cacbdb1ccaf553501066015c5b1dcf22a54b7534d831535748f6b7c56eae1ac

build:
  number: 1
  skip: is_abi3 and not is_python_min
  python:
    version_independent: ${{ is_abi3 }}
  script:
    env:
      CARGO: ${{ cargo_wrapper }}
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
      MATURIN_PEP517_ARGS: --features=abi3
      PYTHONIOENCODING: UTF-8
      PYTHONUTF8: "1"
    content:
      - if: win
        then:
          - set CARGO_HOME=c:\.cg
          - copy "%RECIPE_DIR%\${{ cargo_wrapper }}" "%BUILD_PREFIX%\Library\bin\"
        else:
          - cp "${RECIPE_DIR}/${{ cargo_wrapper }}" "${BUILD_PREFIX}/bin/"
          - chmod 755 "${BUILD_PREFIX}/bin/${{ cargo_wrapper }}"
      - cd dist
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check --check-build-dependencies
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - python
    - if: not osx
      then:
        - clangdev
        - llvmdev
  host:
    - maturin >=1.8,<2.0
    - pip
    - python
    - if: is_abi3
      then:
        - python ${{ python_min }}.*
        - python-abi3
  run:
    - python
    - rdflib >=6.1.1
    - if: is_abi3
      then:
        - python >=${{ python_min }}
        - python-abi3

tests:
  - package_contents:
      strict: true
      files:
        - etc/conda/test-files/reasonable/**
      site_packages:
        - reasonable/**
        - reasonable-${{ version }}.dist-info/**
  - python:
      imports: reasonable
      pip_check: true
      python_version:
        - if: is_abi3
          then:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
          else:
            - "*"
  - files:
      source:
        - src/python/tests/**
        - src/example_models/ontologies/rdfs.ttl
    requirements:
      run:
        - pytest
        - if: is_abi3
          then:
            - python ${{ python_min }}.*
            - abi3audit
    script:
      - cd src/python
      # don't bother with coverage; one generated file with `*` import
      - pytest -vv --tb=long --color=yes
      - if: is_abi3
        then:
          - if: unix
            then: abi3audit -s -v --assume-minimum-abi3 ${{ python_min }} "${SP_DIR}/reasonable/reasonable.abi3.so"
            else: abi3audit -s -v --assume-minimum-abi3 ${{ python_min }} "%SP_DIR%\reasonable\reasonable.pyd"

about:
  summary: An OWL 2 RL reasoner with reasonable performance
  license: BSD-3-Clause
  license_file:
    - dist/LICENSE
    - dist/THIRDPARTY.yml
  homepage: https://pypi.org/project/reasonable
  repository: https://github.com/gtfierro/reasonable

extra:
  recipe-maintainers:
    - bollwyvl
