# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.4.0"
  python_check_max: "3.14"
  abi3_ext: ${{ "pyd" if win else "abi3.so" }}
  unix_sp_dir: |-
    $(python -c "print(__import__('site').getsitepackages()[-1])")/reasonable
  win_sp_dir: |-
    Lib\site-packages\reasonable
  sp_dir: |-
    ${{ "%PREFIX%\\" ~ win_sp_dir if win else unix_sp_dir }}

package:
  name: reasonable
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/reasonable/reasonable-${{ version }}.tar.gz
  sha256: 21dff10a8f587ecce1e5c45e684eceea45dc2484e93973ff1c5ae4545d80840c

build:
  number: 0
  skip: is_abi3 and not is_python_min
  python:
    version_independent: ${{ is_abi3 }}
  script:
    env:
      PYTHONIOENCODING: UTF-8
      PYTHONUTF8: "1"
      MATURIN_PEP517_ARGS: --features=abi3
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - python
    - if: not osx
      then:
        - clangdev
        - llvmdev
  host:
    - maturin >=1.8,<2.0
    - pip
    - python
    - if: is_abi3
      then:
      - python-abi3
  run:
    - python
    - rdflib >=6.1.1

tests:
  - if: is_abi3
    then:
      - python:
          imports: reasonable
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
    else:
      - python:
          imports: reasonable
          pip_check: true
  - files:
      source:
        - python/tests/
    requirements:
      run:
        - pytest-cov
        - if: is_abi3
          then:
            - python ${{ python_check_max }}.*
            - abi3audit
    script:
      - cd python
      - coverage run -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=100
      - if: is_abi3
        then:
          - cd "${{ sp_dir }}"
          - abi3audit -s -v --assume-minimum-abi3 ${{ python_min }} reasonable.${{ abi3_ext }}

about:
  summary: An OWL 2 RL reasoner with reasonable performance
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/reasonable
  repository: https://github.com/gtfierro/reasonable

extra:
  recipe-maintainers:
    - bollwyvl
